server:
  port: 1010
spring:
  mvc:
    view:
      prefix: templates/
      suffix: .html
    static-path-pattern: static/**
  datasource:
    url: jdbc:mysql://localhost:3306/peoject_auto?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
